-- MySQL Script generated by MySQL Workbench
-- Thu Apr  6 00:43:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Olympus_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Olympus_db` ;

-- -----------------------------------------------------
-- Schema Olympus_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Olympus_db` DEFAULT CHARACTER SET utf8 ;
USE `Olympus_db` ;

-- -----------------------------------------------------
-- Table `Olympus_db`.`studente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Olympus_db`.`studente` ;

CREATE TABLE IF NOT EXISTS `Olympus_db`.`studente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cognome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `codice fiscale` VARCHAR(45) NOT NULL,
  `matricola` VARCHAR(45) NOT NULL,
  `corso di studi` VARCHAR(45) NOT NULL,
  `anno iscrizione` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `matricola_UNIQUE` (`matricola` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Olympus_db`.`Amministratore di dipartimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Olympus_db`.`Amministratore di dipartimento` ;

CREATE TABLE IF NOT EXISTS `Olympus_db`.`Amministratore di dipartimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `dipartimento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `dipartimento_UNIQUE` (`dipartimento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Olympus_db`.`Professore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Olympus_db`.`Professore` ;

CREATE TABLE IF NOT EXISTS `Olympus_db`.`Professore` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cognome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `codice fiscale` VARCHAR(45) NOT NULL,
  `matricola` VARCHAR(45) NOT NULL,
  `materia` VARCHAR(45) NOT NULL,
  `Ruolo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `matricola_UNIQUE` (`matricola` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Olympus_db`.`esame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Olympus_db`.`esame` ;

CREATE TABLE IF NOT EXISTS `Olympus_db`.`esame` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(45) NOT NULL,
  `materia` VARCHAR(45) NOT NULL,
  `note` VARCHAR(45) NULL,
  `voto` VARCHAR(45) NULL,
  `professore` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_professore_idx` (`professore` ASC) VISIBLE,
  CONSTRAINT `id_professore`
    FOREIGN KEY (`professore`)
    REFERENCES `Olympus_db`.`Professore` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Olympus_db`.`Esami sostenuti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Olympus_db`.`Esami sostenuti` ;

CREATE TABLE IF NOT EXISTS `Olympus_db`.`Esami sostenuti` (
  `id` INT NOT NULL,
  `id esame` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`id esame` ASC) VISIBLE,
  CONSTRAINT `id_studente`
    FOREIGN KEY (`id`)
    REFERENCES `Olympus_db`.`studente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_esame`
    FOREIGN KEY (`id esame`)
    REFERENCES `Olympus_db`.`esame` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
